### ISSUE TITLE
Rvizの2D Pose Estimationが動かない

### ISSUE THREAD

**Issue by kanpapa** [docofab/RoombaControlls#81]
Rvizの2D Pose Estimationをクリックし、ルンバの位置と向きを地図を合わせるが、実際のルンバの位置をマウスポインタで指定し、緑の矢印をルンバの向きに合うようにドラッグしてもルンバがそのように動かない。
TurtleBot3ではうまく動きます。
ヒントがあったら教えてください。
https://github.com/docofab/RoombaControlls/blob/main/ROS/instructions/slam-navigation-gazebo.md

**Comment by sibafb** [comment]
2D Pose Estimation
はrvizのtool propatiesで発行トピック名が変えられるみたいです、

createのライブラリの自己位置トピックの名前に合わせる必要があると思います


指定の仕方はここを参考ください　2:46とかです。
（私はこの動画で知りました）
https://youtu.be/iyL_hsqjKWI

**Comment by kanpapa** [comment]
ヒントをありがとうございます。 問題なく動作するようになりました。
設定方法を #88 で反映しました。
